openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    API for managing contacts with authentication support.
tags:
  - name: Contacts
    description: Contacts management endpoints
  - name: Auth
    description: Authentication endpoints
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-4-1dto.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
